export const data = [
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Person 1",
    reviewer1: "Reviewer 1",
    reviewer2: "reviwer2",
  },
];
