export const data = [
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
  {
    storyNumber: 23546,
    storyName: "This is Temp Title for story 1 from temp data file",
    storyLink: "https://www.google.com",
    prLink: "https://www.google.com",
    personWorkingOn: "Kaushik Jain",
    reviewer1: "Nitin Sharma",
    reviewer2: "Shivam Raj",
  },
];
